spring:
  profiles:
    active: local
  application:
    name: locke
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  threads:
    virtual:
      enabled: true
  # 数据库连接配置
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    # url: jdbc:h2:file:./data/locke_db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;MODE=MySQL
    # 如果使用文件模式，支持动态查看运行时数据库，但每次启动jpa都会覆盖之前的数据，需要关闭自动插入数据功能
    driver-class-name: org.h2.Driver
    username: sa
    password:

      # H2 控制台配置
  h2:
    console:
      enabled: true

  # JPA/Hibernate 相关配置
  jpa:
    defer-datasource-initialization: true #  Hibernate 先自动建表，再由 data.sql 插入数据
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # 自动根据 Entity 类生成/更新表结构
    show-sql: true # 在控制台打印 SQL 语句，方便调试

  sql:
    init:
      mode: always
      # 无需指定 schema.sql，直接由 Hibernate 根据 Entity 类生成表结构
      data-locations: classpath:data.sql
      continue-on-error: true
server:
  port: 8080
  address: 0.0.0.0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  packages-to-scan: com.newblash.locke.controller

jwt:
  expiration: 604800000
  secret: ${JWT_SECRET:locke_wiki_secret_key_fixed_version_2026_provide_long_enough_string}

# debug: true
logging:
  file:
    name: startup.log
